modLoader = "kotlinforforge"
loaderVersion = "[4.10,)"
license = "All Rights Reserved"

[[mods]]
modId = "arisentity"
version = "${version}"
displayName = "aris-entity"
authors = "Dayo"
description = '''
Aris entity extension
'''

[[dependencies.arisentity]]
modId = "forge"
mandatory = true
versionRange = "[47.3.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.arisentity]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.arisentity]]
modId = "aris"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.arisentity]]
modId = "kotlinforforge"
mandatory = true
versionRange = "[4.10,)"
ordering = "NONE"
side = "BOTH"
